# -*- mode: ruby -*-
# vi: set ft=ruby :

# Bowtie / Mesh Topology
# +---------+e3          e3+---------+
# | spine01 |--------------| spine02 |
# +---------+              +---------+
#   |e1    \ e2          e1 /    e2|
#   |        \            /        |
#   |          \        /          |
#   |            \    /            |
#   |              \/              |
#   |             /  \             |
#   |           /      \           |
#   |         /          \         |
#   |e1     / e2        e1 \     e2|
# +---------+              +---------+
# | leaf03  |--------------| leaf04  |
# +---------+e3          e3+---------+

default_box = 'vEOS-lab-4.17.2F'

Vagrant.configure(2) do |config|

  config.vm.define 'spine01' do |spine01|
    spine01.vm.box = default_box
    spine01.vm.network :forwarded_port, guest: 22, host: 2201, id: 'ssh'
    spine01.vm.network 'private_network',
                       virtualbox__intnet: 's01l03',
                       ip: '169.254.1.11', auto_config: false
    spine01.vm.network 'private_network',
                       virtualbox__intnet: 's01l04',
                       ip: '169.254.1.11', auto_config: false
    spine01.vm.network 'private_network',
                       virtualbox__intnet: 's01s02',
                       ip: '169.254.1.11', auto_config: false
    spine01.vm.provision 'shell', inline: <<-SHELL
      sleep 120
      FastCli -p 15 -c "configure
      hostname spine01
      interface Management1
        description Dette er en test
        ip address 192.168.16.51/24
        no shut
    SHELL
    #  interface Ethernet3
    #     shutdown
  end

  config.vm.define 'spine02' do |spine02|
    spine02.vm.box = default_box
    spine02.vm.network :forwarded_port, guest: 22, host: 2202, id: 'ssh'
    spine02.vm.network 'private_network',
                       virtualbox__intnet: 's02l03',
                       ip: '169.254.1.11', auto_config: false
    spine02.vm.network 'private_network',
                       virtualbox__intnet: 's02l04',
                       ip: '169.254.1.11', auto_config: false
    spine02.vm.network 'private_network',
                       virtualbox__intnet: 's01s02',
                       ip: '169.254.1.11', auto_config: false

    spine02.vm.provision 'shell', inline: <<-SHELL
      sleep 120
      FastCli -p 15 -c "configure
      hostname spine02
      interface Management1
        ip address 192.168.16.52/24 secondary"
    SHELL
  end
  config.vm.define 'leaf03' do |leaf03|
    leaf03.vm.box = default_box
    leaf03.vm.network :forwarded_port, guest: 22, host: 2203, id: 'ssh'
    leaf03.vm.network 'private_network',
                       virtualbox__intnet: 's01l03',
                       ip: '169.254.1.11', auto_config: false
    leaf03.vm.network 'private_network',
                       virtualbox__intnet: 's02l03',
                       ip: '169.254.1.11', auto_config: false
    leaf03.vm.network 'private_network',
                       virtualbox__intnet: 'l03l04',
                       ip: '169.254.1.11', auto_config: false

    leaf03.vm.provision 'shell', inline: <<-SHELL
      sleep 120
      FastCli -p 15 -c "configure
      hostname leaf03
      interface Management1
        ip address 192.168.16.53/24 secondary"
    SHELL
  end
  config.vm.define 'leaf04' do |leaf04|
    leaf04.vm.box = default_box
    leaf04.vm.network :forwarded_port, guest: 22, host: 2204, id: 'ssh'
    leaf04.vm.network 'private_network',
                       virtualbox__intnet: 's01l04',
                       ip: '169.254.1.11', auto_config: false
    leaf04.vm.network 'private_network',
                       virtualbox__intnet: 's02l04',
                       ip: '169.254.1.11', auto_config: false
    leaf04.vm.network 'private_network',
                       virtualbox__intnet: 'l03l04',
                       ip: '169.254.1.11', auto_config: false

    leaf04.vm.provision 'shell', inline: <<-SHELL
      sleep 120
      FastCli -p 15 -c "configure
      hostname leaf04
      interface Management1
        ip address 192.168.16.54/24 secondary"
    SHELL
  end
  config.vm.define 'nms' do |nms|
    nms.vm.box = "phusion/ubuntu-14.04-amd64"
    nms.vm.host_name = "nms"
    nms.vm.network "private_network", 
                    ip: '172.16.1.12'
    nms.vm.network "public_network"
    nms.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = '2048'
    nms.vm.provision 'shell', inline: <<-SHELL
      sleep 60
        apt-get update
        apt-get install -y ansible
    SHELL
  end
 end
end
