- hosts: router
  connection: local
  vars:
  - results: results
  tasks:
    - file: path={{results}} state=directory
      run_once: true
    - file: path={{results}}/uptime.log state=touch
      run_once: true
    - snmp_facts:
        host: "{{ansible_host}}"
        version: v2
        community: cisco
    - name: ssh facts
      register: iosfacts_out
      ios_facts:
        provider: "{{ credentials }}"
    - lineinfile:
        dest:   "{{results}}/uptime.log"
        regexp: "{{inventory_hostname}}"
        line:  |
          {{'%20s %8s'|format(inventory_hostname,ansible_sysuptime)}}